name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Get the repository
      - name: Checkout
        uses: actions/checkout@v6

      # Install Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build React app
      - name: Build
        run: npm run build

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload React build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build

      # Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4